version: "3.9"

services:

  cetusguard:
    container_name: "cetusguard"
    image: "docker.io/hectorm/cetusguard:v1"
    restart: "on-failure"
    read_only: true
    networks:
      - "cetusguard-private"
      - "cetusguard-public"
    volumes:
      - "./rules.list:/rules.list:ro"
    environment:
      CETUSGUARD_BACKEND_ADDR: "tcp://podmand:2375"
      CETUSGUARD_FRONTEND_ADDR: "tcp://:2375"
      CETUSGUARD_RULES_FILE: "/rules.list"
      CETUSGUARD_LOG_LEVEL: "7"
    depends_on:
      - "podmand"

  podmand:
    container_name: "cetusguard-podmand"
    image: "quay.io/podman/stable:v4"
    restart: "on-failure"
    privileged: true
    networks:
      - "cetusguard-private"
    entrypoint: "/usr/bin/podman"
    command: ["system", "service", "--time=0", "tcp://:2375"]

  podman:
    container_name: "cetusguard-podman"
    image: "quay.io/podman/stable:v4"
    restart: "on-failure"
    stop_signal: "SIGKILL"
    networks:
      - "cetusguard-public"
    environment:
      CONTAINER_HOST: "tcp://cetusguard:2375"
    entrypoint: "/bin/sh"
    command: ["-c", "while :; do sleep 60; done"]
    depends_on:
      - "cetusguard"

networks:

  cetusguard-private:
    name: "cetusguard-private"

  cetusguard-public:
    name: "cetusguard-public"
