name: 'e2e'

on:
  push:
    tags: ['*']
    branches: ['*']
  pull_request:
    branches: ['*']
  workflow_dispatch:

jobs:

  e2e:
    name: 'e2e test'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
    env:
      DOCKER_CLI_REMOTE: 'https://github.com/docker/cli.git'
      DOCKER_CLI_TREEISH: '429d716fbc11423f174490d448a78047928301c3'
      CONTAINER_LOG_TAG: '${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}'
    steps:
      - name: 'Checkout project'
        uses: 'actions/checkout@v3'
      - name: 'Checkout docker/cli project'
        run: |
          mkdir /tmp/docker-cli/ && cd /tmp/docker-cli/
          git clone "${DOCKER_CLI_REMOTE:?}" /tmp/docker-cli/
          git checkout "${DOCKER_CLI_TREEISH:?}"
      - name: 'Patch docker/cli project'
        working-directory: '/tmp/docker-cli/'
        run: |
          git apply -v <<'EOF'
          diff --git a/e2e/compose-env.yaml b/e2e/compose-env.yaml
          index a4c700c465..6705181da3 100644
          --- a/e2e/compose-env.yaml
          +++ b/e2e/compose-env.yaml
          @@ -7,2 +7,13 @@ services:
             engine:
          +    image: 'localhost.test/cetusguard:latest'
          +    restart: 'on-failure'
          +    logging: { driver: 'journald', options: { tag: '${CONTAINER_LOG_TAG:?}' } }
          +    read_only: true
          +    environment:
          +      CETUSGUARD_BACKEND_ADDR: 'tcp://engine-shaded:2375'
          +      CETUSGUARD_FRONTEND_ADDR: 'tcp://:2375'
          +      CETUSGUARD_RULES: 'GET,HEAD,POST,PUT,DELETE /.+'
          +      CETUSGUARD_LOG_LEVEL: '7'
          +
          +  engine-shaded:
                 image: 'docker:${TEST_ENGINE_VERSION:-stable-dind}'
          EOF
          git apply -v <<EOF
          diff --git a/e2e/.env b/e2e/.env
          new file mode 100644
          index 0000000000..b1ce7e48c9
          --- /dev/null
          +++ b/e2e/.env
          @@ -0,0 +1 @@
          +CONTAINER_LOG_TAG=${CONTAINER_LOG_TAG:?}
          EOF
      - name: 'Build Docker image'
        run: |
          docker build --tag 'localhost.test/cetusguard:latest' ./
      - name: 'Run e2e test'
        working-directory: '/tmp/docker-cli/'
        run: |
          make -f ./docker.Makefile test-e2e-non-experimental
      - name: 'Check e2e test log'
        if: 'always()'
        run: |
          journalctl --output=cat CONTAINER_TAG="${CONTAINER_LOG_TAG:?}"
          test -n "$(journalctl --output=cat CONTAINER_TAG="${CONTAINER_LOG_TAG:?}" | head -n1)"
          test -z "$(journalctl --output=cat CONTAINER_TAG="${CONTAINER_LOG_TAG:?}" | grep -v '^\(WARNING\|INFO\|DEBUG\):')"
